---
kind: pipeline
name: default

env: &env
  MOJO_MODE: development
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres

steps:
  - name: test
    image: perl:5.28.1-threaded
    environment:
      <<: *env
    commands:
      - cpanm Carton
      - carton install
      - carton exec -- prove -lv

  - name: notify-slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: webhook_url