---
kind: pipeline
name: default

steps:
  - name: test
    image: perl:5.28.1-slim-threaded
    commands:
      - cpanm Carton
      - carton install
      - carton exec -- prove -lv

  - name: notify-slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: webhook_url