version: "3"

services:
  app:
    build: .
    volumes:
    - ".:/app"
    ports:
    - "3000:3000"
    environment:
      MOJO_MODE: development
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db_data: