version: "3"

services:
  app:
    build: .
    volumes:
    - ".:/app"
    ports:
    - "3000:3000"
    env_file: .env.dev
    stdin_open: true
    tty: true
  db:
    image: postgres:11.4-alpine
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: app_development
      POSTGRES_PASSWORD: postgres

volumes:
  db_data: