version: "3"

services:
  app:
    build: .
    volumes:
    - ".:/app"
    ports:
    - "3000:3000"
    env_file: .env.dev
    stdin_open: true
    tty: true
    depends_on:
    - db
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    ports:
    - 5432:5432
    environment:
      MYSQL_DATABASE: app_development
      MYSQL_ROOT_PASSWORD: secret

volumes:
  db_data: